//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ScrollBar.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SCROLLBAR_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDB_VERTICLE_SCROLLBAR_DOWNARROW 129
#define IDB_VERTICLE_SCROLLBAR_UPARROW  130
#define IDB_VERTICLE_SCROLLBAR_SPAN     131
#define IDB_VERTICLE_SCROLLBAR_SLIDER_TOP 132
#define IDB_VERTICLE_SCROLLBAR_SLIDER_BOTTOM 133
#define IDB_VERTICLE_SCROLLBAR_SLIDER_CENTER 134
#define IDB_VERTICLE_SCROLLBAR_THUMB    135
#define IDB_HORIZONTAL_SCROLLBAR_LEFTARROW 136
#define IDB_HORIZONTAL_SCROLLBAR_RIGHTARROW 137
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_CENTER 138
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_LEFT 139
#define IDB_HORIZONTAL_SCROLLBAR_THUMB  140
#define IDB_HORIZONTAL_SCROLLBAR_SLIDER_RIGHT 141
#define IDB_HORIZONTAL_SCROLLBAR_SPAN   142
#define IDC_TREE1                       1000
#define IDC_LIST1                       1001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
