
#ifndef MESSAGE_ID_H
#define MESSAGE_ID_H

enum e_MIDMSG
{
    PAMSG_MID_LIFE_SIGNAL = 0,
    PAMSG_MID_BUSY_STATE = 1,
    PAMSG_MID_CONNECT = 2,
    PAMSG_MID_TIMESYNC = 3,
    PAMSG_MID_VOLUME = 4
};

enum e_VOLUME_SUBMID
{
    SMID_SET_VOLUME = 1,
    SMID_SET_STEP_VOLUME = 2,
    SMID_VOLUME_NOTIFY = 3,

    SMID_LEVEL_METER_START = 4,
    SMID_LEVEL_METER_STOP = 5,
    SMID_LEVEL_METER_DATA = 6
};

enum e_CONNECT_REQUEST
{
    CON_ACTIVATE = 1,
    CON_DEACTIVATE = 2,
    CON_REACTIVATE = 3,
    CON_INTERRUPT = 4,
    CON_ROUTESTATE = 5,
    CON_CHECKROUTE = 6
};

enum e_CONNECT_RESPONE
{
    CON_ON_ACTIVATE = 1001,
    CON_ON_DEACTIVATE = 1002,
    CON_ON_REACTIVATE = 1003,
    CON_ON_INTERRUPT = 1004,
    CON_ON_ROUTESTATE = 1005,
    CON_ON_CHECKROUTE = 1006
};

#endif

